---

  - yum: name=httpd state=installed

  - service: name=httpd state=started enabled=true

  - firewalld: service={{ item }} permanent=true state=enabled
    notify: reload firewalld
    with_items: 
      - http
      - https
