## see http://docs.ansible.com/guide_rax.html
## deployment requires pyrax module - yum install python-pyrax

---

- hosts: localhost
  gather_facts: False
  tasks:
    
    - name: Get my username
      command: whoami
      register: whoami

    - name: Add keypair
      rax_keypair:
        credentials: ~/.rackspace_cloud_credentials
        name: "{{ whoami.stdout }}_ssh_key"
        public_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
        region: ORD
      register: keypair
 
    - debug: var=keypair

    - name: Build http server
      rax:
        credentials: ~/.rackspace_cloud_credentials
        name: chilug-ansible-web
        flavor: 3
        region: ORD
        image: f0d3b38b-61e3-47c4-83c7-98c4e7038809
        count: 1
        wait: yes
        key_name: "{{ keypair.keypair.id }}"
        networks:
          - public
      register: webservers
       
    - debug: var=webservers

    - name: Group up the http hosts
      add_host:
        hostname: "{{ item.name }}"
        ansible_ssh_host: "{{ item.accessIPv4 }}"
        groupname: raxweb
      with_items: webservers.instances

- hosts: raxweb
  remote_user: root
  roles: 
    - nginx
    - chicago-lug-nginx-config
